// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7WfE8RynGOiREqHdKfTFb75PxZp5Lxrg',
    appId: '1:916434419383:web:d445965dda4b6bfbc31732',
    messagingSenderId: '916434419383',
    projectId: 'learn-flutter-68-2',
    authDomain: 'learn-flutter-68-2.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2.firebasestorage.app',
    measurementId: 'G-CNFZEKX9S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg58SWmGDp6Tbhj7TkbWd1ys21rnDZGFc',
    appId: '1:916434419383:android:cf4cd9db7025715cc31732',
    messagingSenderId: '916434419383',
    projectId: 'learn-flutter-68-2',
    storageBucket: 'learn-flutter-68-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVwtfZtV2ro5m7_qsQOkjGuM9-Tp5M5WM',
    appId: '1:916434419383:ios:b91711f8582b2f99c31732',
    messagingSenderId: '916434419383',
    projectId: 'learn-flutter-68-2',
    storageBucket: 'learn-flutter-68-2.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVwtfZtV2ro5m7_qsQOkjGuM9-Tp5M5WM',
    appId: '1:916434419383:ios:b91711f8582b2f99c31732',
    messagingSenderId: '916434419383',
    projectId: 'learn-flutter-68-2',
    storageBucket: 'learn-flutter-68-2.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter6822',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7WfE8RynGOiREqHdKfTFb75PxZp5Lxrg',
    appId: '1:916434419383:web:c0f4a0c56bfe887dc31732',
    messagingSenderId: '916434419383',
    projectId: 'learn-flutter-68-2',
    authDomain: 'learn-flutter-68-2.firebaseapp.com',
    storageBucket: 'learn-flutter-68-2.firebasestorage.app',
    measurementId: 'G-MLEEQC52QY',
  );
}
